### ISSUE TITLE
Error: getpwnam("nobody") disabled for static build (38: Function not implemented)

### ISSUE THREAD

**Issue by crestone** [ericpruitt/static-nginx#4]
After modification of your Makefile (see pull requests)
I get some errors after run nginx binary:

```
src/objs/nginx -c /usr/src/nginx/static-nginx/src/conf/nginx.conf -t
nginx: [alert] could not open error log file: open() "../nginx/logs/error.log" failed (2: No such file or directory)
nginx: the configuration file /usr/src/nginx/static-nginx/src/conf/nginx.conf syntax is ok
2016/08/06 21:50:52 [emerg] 23439#0: getpwnam("nobody") disabled for static build (38: Function not implemented)
nginx: configuration file /usr/src/nginx/static-nginx/src/conf/nginx.conf test failed
```

What could be the reason of this?

**Comment by ericpruitt** [comment]
Are trying to start NGINX as root? If so, you can't do that. You'll have to use iptables forwarding or something similar. I think I know how to modify the code to make it possible to start the server as root and then have it drop privileges the traditional way, but since I typically don't run services as root, I never bothered; deleting things is typically easier and faster than adding them `;)`. I'll take a look later and see just how much work it would actually be and follow-up with you.

If you aren't running NGINX as root, please attach the configuration files you're using so I can try to replicate the problem.

**Comment by crestone** [comment]
Yes, you are right I was trying run Nginx as a root.
Configuration was from stock bundle.
In fact, I need a static binary to run in a Docker container and therefore be able to run as root.
Also need to include in the build a third-party library for Nginx module.
How it can be difficult and why the user can't be specified for the static build?

**Comment by ericpruitt** [comment]
Unfortunately, not all functions can be statically linked which causes the resulting binaries to be dependent on whatever version of GNU libc (glibc) the application was compiled with. Most issues typically revolve around [Name Service Switch (NSS)][NSS]. NSS allows system administrators to reconfigure a system to use external sources for things that would normally be queried from `/etc/passwd`, `/etc/shadow`, `/etc/hosts`, `/etc/groups`, `/etc/resolv.conf`, etc.; think of services provided by things like LDAP, Active Directory and Windows Domain Controllers.

The `getpwnam(3)`, which is used to get information about a user, is one of those functions. To work around this issue, I would need to replace `getpwnam(3)` probably with code from [musl](https://www.musl-libc.org/). If the Docker container is using the same version of glibc as the CentOS image you're using, then you can try the following:
1. Delete the NGINX source code folder, nginx-src and any binaries that have been built.
2. In the Makefile, delete this line: `cd src && patch -p1 < ../static-nginx.patch`
3. Build NGINX

You will see warnings in the output like "misc1.c:…: warning: … requires … the glibc version used for linking;" ignore them. Copy the compiled NGINX binary into the Docker container and see if it works. If it works, then that means you don't _need_ the patch I use to disable NSS functions.

**Comment by crestone** [comment]
Thanks for that I'll try it

**Comment by crestone** [comment]
I commented patch command and compiled. Now runs well, thanks!
But I still need to compile some of the 3rd modules including library dependencies, can you give me some advice?

**Comment by ericpruitt** [comment]
Sure -- I've never used NGINX with any third-party modules, but I will try to help. Exactly which modules are you having problems with? Can you paste the build errors you're seeing and any flags you're adding that aren't in the Makefile?

**Comment by crestone** [comment]
First I need to compile this https://github.com/crestone/ngx_http_ip2location_module module with this https://github.com/crestone/IP2Location-C-Library library.
Before I compiled all good but before to compile Nginx module I was must compile Lib and install it. Now an idea to compile all in one place, I mean in Nginx binary.
But I have some misunderstood how to configure build params for it

**Comment by ericpruitt** [comment]
I'm going to follow-up over email since this conversation has veered off topic from the original issue.

**Comment by Nottt** [comment]
Thanks! I googled a lot before I found this, and yes if you run nginx as root for some reason `getpwnam` will fail....

Unfortunately for my software, running the nginx without root gives other issues :/

**Comment by wanglong001** [comment]
@Nottt @ericpruitt  @crestone 
Is there a better way? Use root user to run static nginx binary

**Comment by wanglong001** [comment]
@ericpruitt 
```
I would need to replace getpwnam(3) probably with code from musl.
```

Thanks！[musl](https://www.musl-libc.org/) , It works for me
