### ISSUE TITLE
Compilation fails for 1.13.6

### ISSUE THREAD

**Issue by DJGummikuh** [ericpruitt/static-nginx#6]
Hey! I tried building the current mainline version of nginx (1.13.6), which fails. Please take a look at the generated output:
[https://nopaste.xyz/?bc0f92be0a1a420d#qRKK6xDaoYQ2XHSyHNZ1cvTeb8c8sEe13KwuUFYj/mI=](https://nopaste.xyz/?bc0f92be0a1a420d#qRKK6xDaoYQ2XHSyHNZ1cvTeb8c8sEe13KwuUFYj/mI=)

What am I doing wrong?

**Comment by DJGummikuh** [comment]
Issue could be solved by patching nginx Source with patch from https://trac.nginx.org/nginx/ticket/1259

**Comment by ericpruitt** [comment]
Thank you for both reporting the issue and explaining how you resolved it. I've updated the version of NGINX, OpenSSL and PCRE used in 86bae906250187ddc1022246726820e84cc70382.
